apiVersion: v1
kind: Service
metadata:
  name: flask-webapp-service
spec:
  selector:
    app: flask-webapp
  ports:
  - port: 8080
    targetPort: 8080
    nodePort: 30010
  type: NodePort  
